#! /usr/bin/python3
import subprocess
import os

script_status = 0
remove_cmd = 'rm -rf node_modules && rm -rf lib'
install_cmd = 'npm i && npm run build'
cmd = remove_cmd + ' && ' + install_cmd

def search_and_destroy():
	script_status = subprocess.run('cd packages/types && '+ cmd, shell=True).returncode
	if script_status < 1:
		script_status = subprocess.run('cd packages/internal && '+ cmd, shell=True).returncode
		if script_status < 1:
			script_status = subprocess.run('cd packages/flavors && '+ cmd, shell=True).returncode

search_and_destroy()

if script_status < 1:
	script_status = subprocess.run('rm -rf node_modules && rm -rf bin && npm i && ./scripts/relink-pkg', shell=True).returncode
