// export * from './flavor';
export * from './types';
export * from './copy-dir';
export * from './sys-info';
export * from './logger';
export * from './subprocess';
export * from './valid-write-path';
export * from './config';
exports.CRUMB_FILE_MAP = require('./.config/crumbfilemap.json');
exports.__DEFAULTS__ = require('./.config/.defaults.json');
exports.__FLAVORS__ = require('./.config/flavors.json');
export { Inquirer, prompt } from 'inquirer';
