#!/usr/bin/python3

import string
import sys, time, os
from py_console import console
from halo import Halo
from spinners import Spinners

@Halo(text='Looking for Config', spinner=Spinners.bouncingBall.value)
def find_config():
	path: string
	time.sleep(1)
	if(len(sys.argv) > 1):
		path = sys.argv[2]
	else:
		path = os.getcwd()
	print('\n')
	return path

def main():
	path = find_config()
	console.info('base path:')
	print(path)

if __name__ == '__main__':
	main()
